import { ArrowDown, BrainCircuit, Database, GitMerge, Scale, ShieldCheck } from "lucide-react";
import { SiteFooter, SiteHeader } from "@/components/site-header";
import { ACC_METRICS } from "@/lib/site-data";

export default function ResearchPage(){return <><SiteHeader/><main className="site-shell subpage"><header className="research-hero"><span className="eyebrow">Mode penelitian privat</span><h1>Model yang transparan, hasil yang tidak dilebihkan.</h1><p>Ringkasan visual untuk area penelitian yang hanya dapat dibuka setelah masuk. Holdout pernah dilihat dalam pengembangan, sehingga hasil ini bersifat eksploratif.</p><div className="research-session"><span>Sesi penelitian aktif</span><a href="/api/auth/logout?return_to=/">Keluar</a></div></header><section className="research-stats"><Stat value="5.110" label="baris data" detail="249 label stroke"/><Stat value="4,87%" label="prevalensi" detail="rasio sekitar 1 : 19,5"/><Stat value="82%" label="recall stacking" detail="41 dari 50 label positif"/><Stat value="15,41%" label="precision stacking" detail="false alarm masih tinggi"/></section>
  <section className="research-panel"><div className="section-heading"><span className="icon-box"><GitMerge/></span><div><span className="eyebrow">Arsitektur ACC</span><h2>Tiga sudut pandang, satu keputusan akhir</h2></div></div><div className="architecture"><div className="base-stack"><ModelNode name="XGBoost" note="xgb_w50"/><ModelNode name="LightGBM" note="lgb_reg_eng"/><ModelNode name="CatBoost" note="cat_w75"/></div><ArrowDown className="architecture-arrow"/><div className="meta-node"><span>Logit probabilities</span><strong>Logistic Regression</strong><small>L2 · C=0,01 · threshold OOF terkendala</small></div></div><div className="method-notes"><p><ShieldCheck/>Preprocessing dan bobot kelas berada di dalam fold training.</p><p><Scale/>Threshold utama dipilih dari OOF: recall ≥82,5% dan accuracy ≥70%.</p><p><Database/>Konfigurasi final tidak memakai SMOTE.</p></div></section>
  <section className="research-panel"><div className="section-heading"><span className="icon-box"><BrainCircuit/></span><div><span className="eyebrow">Evaluasi holdout historis</span><h2>Kinerja model pada endpoint screening</h2></div></div><div className="table-scroll"><table className="metric-table"><thead><tr><th>Model</th><th>Accuracy</th><th>Recall</th><th>Precision</th><th>F2</th><th>ROC AUC</th><th>PR AUC</th></tr></thead><tbody>{ACC_METRICS.map(row=><tr key={row.model} className={row.featured?"featured":""}><td>{row.model}{row.featured&&<small>Final</small>}</td><td>{row.accuracy}</td><td>{row.recall}</td><td>{row.precision}</td><td>{row.f2}</td><td>{row.roc}</td><td>{row.pr}</td></tr>)}</tbody></table></div><p className="table-note">PR AUC XGBoost sedikit lebih tinggi; stacking unggul pada accuracy, recall bersama LightGBM, F2, dan ROC AUC. Tidak ada klaim bahwa stacking menang pada setiap metrik.</p></section>
  <section className="shap-grid"><div className="research-panel"><span className="level-number">01</span><span className="eyebrow">SHAP tingkat ensemble</span><h2>Model mana yang mendorong keputusan?</h2><p>LinearExplainer membaca kontribusi logit probabilitas XGBoost, LightGBM, dan CatBoost terhadap Logistic Regression.</p><div className="concept-bars"><i style={{width:"88%"}}/><i style={{width:"76%"}}/><i style={{width:"62%"}}/></div><small className="illustration-label">Ilustrasi struktur, nilai numerik mengikuti output Colab final.</small></div><div className="research-panel"><span className="level-number">02</span><span className="eyebrow">SHAP tingkat fitur</span><h2>Faktor apa yang mengubah skor?</h2><p>KernelExplainer mengikuti pipeline penuh untuk menjelaskan usia, glukosa, BMI, hipertensi, penyakit jantung, dan fitur lainnya.</p><div className="shap-flow"><span>Profil pasien</span><ArrowDown/><span>Pipeline penuh</span><ArrowDown/><span>Kontribusi fitur</span></div><small className="illustration-label">SHAP menjelaskan perilaku model, bukan sebab penyakit.</small></div></section>
  <section className="research-disclaimer"><strong>Batas penggunaan</strong><p>Dataset tidak menetapkan horizon risiko prospektif dan model belum divalidasi eksternal atau klinis. NeuroLume hanya cocok untuk demonstrasi penelitian dan edukasi sebelum skrining.</p></section></main><SiteFooter/></>}
function Stat({value,label,detail}:{value:string;label:string;detail:string}){return <div><strong>{value}</strong><span>{label}</span><small>{detail}</small></div>}
function ModelNode({name,note}:{name:string;note:string}){return <div className="model-node"><strong>{name}</strong><small>{note}</small></div>}
